apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  namespace: rhdh
  name: packages
spec:
  targets:
    - ./backstage-community-plugin-acr.yaml
    - ./backstage-community-plugin-analytics-provider-segment.yaml
    - ./backstage-community-plugin-catalog-backend-module-keycloak.yaml
    - ./backstage-community-plugin-catalog-backend-module-pingidentity.yaml
    - ./backstage-community-plugin-quay-backend.yaml
    - ./backstage-community-plugin-quay.yaml
    - ./backstage-community-plugin-rbac.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-kubernetes.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-quay.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-regex.yaml
    - ./backstage-community-plugin-tech-radar-backend.yaml
    - ./backstage-community-plugin-tech-radar.yaml
    - ./backstage-community-plugin-tekton.yaml
    - ./backstage-community-plugin-topology.yaml
    - ./backstage-plugin-catalog-backend-module-github-org.yaml
    - ./backstage-plugin-catalog-backend-module-github.yaml
    - ./backstage-plugin-catalog-backend-module-gitlab-org.yaml
    - ./backstage-plugin-catalog-backend-module-gitlab.yaml
    - ./backstage-plugin-catalog-backend-module-ldap.yaml
    - ./backstage-plugin-catalog-backend-module-msgraph.yaml
    - ./backstage-plugin-events-backend-module-github.yaml
    - ./backstage-plugin-events-backend-module-gitlab.yaml
    - ./backstage-plugin-kubernetes-backend.yaml
    - ./backstage-plugin-kubernetes.yaml
    - ./backstage-plugin-notifications-backend-module-email.yaml
    - ./backstage-plugin-notifications-backend.yaml
    - ./backstage-plugin-notifications.yaml
    - ./backstage-plugin-scaffolder-backend-module-github.yaml
    - ./backstage-plugin-scaffolder-backend-module-gitlab.yaml
    - ./backstage-plugin-signals-backend.yaml
    - ./backstage-plugin-signals.yaml
    - ./backstage-plugin-techdocs-backend.yaml
    - ./backstage-plugin-techdocs-module-addons-contrib.yaml
    - ./backstage-plugin-techdocs.yaml
    - ./bcp-ctlg-backend-mod-scaffolder-relation-processor.yaml
    - ./red-hat-developer-hub-backstage-plugin-bulk-import-backend.yaml
    - ./red-hat-developer-hub-backstage-plugin-bulk-import.yaml
    - ./red-hat-developer-hub-backstage-plugin-dynamic-home-page.yaml
    - ./red-hat-developer-hub-backstage-plugin-global-header.yaml
    - ./red-hat-developer-hub-backstage-plugin-homepage-backend.yaml
    - ./rhdh-bsp-adoption-insights-backend.yaml
    - ./rhdh-bsp-adoption-insights.yaml
    - ./rhdh-bsp-analytics-mod-adoption-insights.yaml
    - ./rhdh-bsp-ctlg-backend-mod-extensions.yaml
    - ./rhdh-bsp-extensions-backend.yaml
    - ./rhdh-bsp-extensions.yaml
    - ./rhdh-bsp-lightspeed-backend.yaml
    - ./rhdh-bsp-lightspeed.yaml
    - ./rhdh-bsp-orchestrator-backend-mod-loki.yaml
    - ./rhdh-bsp-orchestrator-backend.yaml
    - ./rhdh-bsp-orchestrator-form-widgets.yaml
    - ./rhdh-bsp-orchestrator.yaml
    - ./rhdh-bsp-quickstart.yaml
    - ./rhdh-bsp-scaffolder-backend-mod-orchestrator.yaml
    - ./roadiehq-backstage-plugin-argo-cd-backend.yaml
    - ./roadiehq-scaffolder-backend-argocd.yaml
    - ./roadiehq-scaffolder-backend-module-http-request.yaml
