apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-signals
  namespace: rhdh
  title: "Signals Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/signals
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/signals
  tags: []
spec:
  packageName: "@backstage/plugin-signals"
  # Tag: bs_1.52.0__0.0.32, Build date: 2026-06-02T17:30:32Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-signals@sha256:27c1402d8f6fea0207d9e3f7e85703620fad5516e788bff64e812352c575fe50"
  version: 0.0.32
  backstage:
    role: frontend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - signals-frontend
  appConfigExamples:
    - title: Default configuration (Signals registers the client API; no routes)
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-signals: {}
