apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-auth-backend-module-microsoft-provider
  namespace: rhdh
  title: "Auth Backend Module Microsoft Provider"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/auth-backend-module-microsoft-provider
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/auth-backend-module-microsoft-provider
  tags:
    - authentication
spec:
  packageName: "@backstage/plugin-auth-backend-module-microsoft-provider"
  # Tag: bs_1.52.0__0.3.16
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-auth-backend-module-microsoft-provider@sha256:288c2538ca2332e4fa130d86f9fc321f95912c099b51de3b97f10ccb1773defa"
  version: 0.3.16
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - backstage-plugin-auth-backend-module-microsoft-provider
  appConfigExamples:
    - title: Default configuration
      content:
        auth:
          providers:
            microsoft:
              production:
                clientId: ${MICROSOFT_CLIENT_ID}
                clientSecret: ${MICROSOFT_CLIENT_SECRET}
                tenantId: ${MICROSOFT_TENANT_ID}
                signIn:
                  resolvers:
                    - resolver: emailMatchingUserEntityProfileEmail
