apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-kubernetes
  namespace: rhdh
  title: "Kubernetes Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/kubernetes
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/kubernetes
  tags: []
spec:
  packageName: "@backstage/plugin-kubernetes"
  # Tag: bs_1.54.9__0.12.22, Build date: 2026-06-02T17:33:17Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-kubernetes@sha256:05115ab910c142ffb76b54a282550cbce5a2915725b7f404375d4dc02d001a50"
  version: 0.12.22
  backstage:
    role: frontend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - kubernetes
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-kubernetes:
              mountPoints:
                - mountPoint: entity.page.kubernetes/cards
                  importName: EntityKubernetesContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      anyOf:
                        - hasAnnotation: backstage.io/kubernetes-id
                        - hasAnnotation: backstage.io/kubernetes-namespace
