apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-kubernetes
  namespace: rhdh
  title: "Kubernetes Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/kubernetes
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/kubernetes
  tags: []
spec:
  packageName: "@backstage/plugin-kubernetes"
  # Tag: bs_1.52.0__0.12.20, Build date: 2026-06-02T17:33:17Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-kubernetes@sha256:d1423ca7540a4450a97166a3e5af6a0a781d8b9eee876f6dc01ee1c183f32b5c"
  version: 0.12.20
  backstage:
    role: frontend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - kubernetes
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-kubernetes:
              mountPoints:
                - mountPoint: entity.page.kubernetes/cards
                  importName: EntityKubernetesContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      anyOf:
                        - hasAnnotation: backstage.io/kubernetes-id
                        - hasAnnotation: backstage.io/kubernetes-namespace
