apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-techdocs-backend
  namespace: rhdh
  title: "TechDocs Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/techdocs-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/techdocs-backend
  tags: []
spec:
  packageName: "@backstage/plugin-techdocs-backend"
  # Tag: bs_1.52.0__2.2.1, Build date: 2026-05-21T21:24:29Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-techdocs-backend@sha256:34ad6c826e3a7ad523dcf31b9674e498f6cfbcab54cb6c23d3606d343f65b5d4"
  version: 2.2.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - techdocs
  appConfigExamples:
    - title: Default configuration
      content:
        techdocs:
          builder: local
          generator:
            runIn: local
          publisher:
            type: local
