apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-tekton
  namespace: rhdh
  title: Tekton
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/tekton
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/tekton
  tags: []
spec:
  packageName: '@backstage-community/plugin-tekton'
  # Tag: bs_1.49.4__3.37.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-tekton@sha256:ff8d2810c9eaee7e09191ac8c4f34af60bd9a98f1be29b47eef6ce37732bb265"
  version: 3.39.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - tekton
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-tekton:
              translationResources:
                - importName: tektonTranslations
                  ref: tektonTranslationRef
              mountPoints:
                - mountPoint: entity.page.ci/cards
                  importName: TektonCI
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isTektonCIAvailable
