apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-homepage-backend
  namespace: rhdh
  title: Homepage Backend
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/homepage
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/homepage
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-homepage-backend"
  # Tag: 1.11--0.1.1, Build date: 2026-05-22T15:16:41Z
  dynamicArtifact: "oci://quay.io/rhdh/red-hat-developer-hub-backstage-plugin-homepage-backend@sha256:517fcea03d5a173345fa6a4e9e94864d4064ba950b67d3bd14c977af13686573"
  version: 0.1.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - home-page
  appConfigExamples:
    - title: Default configuration
      content:
        homepage:
          defaultWidgets:
            - id: rhdh-onboarding-section
              props:
                title: Onboarding section
            - id: rhdh-entity-section
              props:
                title: Entity section
            - id: rhdh-template-section
              props:
                title: Template section
