apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-kubernetes-mcp-extras
  namespace: rhdh
  title: "@red-hat-developer-hub/backstage-plugin-kubernetes-mcp-extras"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/mcp-integrations/plugins/kubernetes-mcp-extras
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/mcp-integrations/plugins/kubernetes-mcp-extras
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-kubernetes-mcp-extras"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-kubernetes-mcp-extras:bs_1.54.6__0.2.0
  version: 0.2.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: dev-preview
  lifecycle: active
  partOf:
    - kubernetes-mcp-extras
  appConfigExamples:
    - title: Default configuration
      content:
        backend:
          actions:
            pluginSources:
              - 'kubernetes-mcp-extras'
              - 'scaffolder-mcp-extras'
              - 'software-catalog-mcp-extras'
              - 'techdocs-mcp-extras'
