apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-app-defaults
  namespace: rhdh
  title: App Defaults
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/app-defaults/plugins/app-defaults
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/app-defaults/plugins/app-defaults
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-app-defaults"
  # Tag: bs_1.54.9__1.10.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-app-defaults@sha256:8fc948153bb913079e96cb9517b18762c40337412cc38f651000af445d3d1b01"
  version: 1.10.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - app-defaults
  appConfigNotRequired: true
  appConfigExamples: []
