apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: redhat-backstage-plugin-scaffolder-backend-module-orchestrator
  namespace: rhdh
  title: "Scaffolder Backend Module Orchestrator"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/scaffolder-backend-module-orchestrator
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/scaffolder-backend-module-orchestrator
  tags:
    - software-templates
    - automation
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-scaffolder-backend-module-orchestrator"
  # Tag: 1.11--1.5.4, Build date: 2026-05-26T12:41:42Z
  dynamicArtifact: "oci://quay.io/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator@sha256:e8cb33e40f6f846adaf5e0446049d5a2a5e93a2a12cf8b610e3e0e346f98005c"
  version: 1.5.4
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - orchestrator-scaffolder-actions
  appConfigExamples:
    - title: Default configuration
      content:
        orchestrator:
          dataIndexService:
            url: http://sonataflow-platform-data-index-service
