apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-bsp-scorecard-backend-mod-code-coverage
  namespace: rhdh
  title: "Scorecard Backend Module for Code Coverage"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-code-coverage
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-code-coverage
  tags:
    - analytics
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-scorecard-backend-module-code-coverage"
  # Tag: bs_1.54.9__0.1.3
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-code-coverage@sha256:c4f700806342b36cbc512606bc741b68ca28629cb51d42ff9d4f54e4639eedef"
  version: 0.1.3
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Red Hat
  support: dev-preview
  lifecycle: active
  partOf:
    - scorecard
  appConfigNotRequired: true
  appConfigExamples: []
