apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-scaffolder-backend-module-http-request
  namespace: rhdh
  title: "Scaffolder Backend Module HTTP Request"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request
  annotations:
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request
  tags:
    - software-templates
spec:
  packageName: "@roadiehq/scaffolder-backend-module-http-request"
  # Tag: bs_1.49.4__5.6.0, Build date: 2026-05-26T12:41:25Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/roadiehq-scaffolder-backend-module-http-request@sha256:48d0dc8af52f8fdea6e6d7d55193a4e8eb81c93e0b337e4b103b90f50a970eb1"
  version: 5.6.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
    author: Roadie
  support: generally-available
  lifecycle: active
  partOf:
    - http-request-scaffolder-action
  appConfigNotRequired: true
  appConfigExamples: []
