apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-scaffolder-backend-module-quay
  namespace: rhdh
  title: "Scaffolder Backend Module Quay"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/quay
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/quay
  tags:
    - software-templates
spec:
  packageName: "@backstage-community/plugin-scaffolder-backend-module-quay"
  # Tag: bs_1.52.0__2.21.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-scaffolder-backend-module-quay@sha256:9c669a3af16f3d16219a11885396e9e9cdd379a2ce6689381f63697d0661b637"
  version: 2.21.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - quay-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
