apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-azure-devops-backend
  namespace: rhdh
  title: "Azure DevOps Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/azure-devops
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/azure-devops
  tags: []
spec:
  packageName: "@backstage-community/plugin-azure-devops-backend"
  # Tag: bs_1.52.0__0.30.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-azure-devops-backend@sha256:ccad0877e4e36dba814d121990ec357fe5788885e6e793b7654b9974e821f1d1"
  version: 0.30.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - azure-devops
  appConfigExamples:
    - title: Default configuration
      content:
        azureDevOps:
          host: dev.azure.com
          token: ${AZURE_TOKEN}
          organization: ${AZURE_ORG}
          pullRequestDashboard:
            organizations:
              - organization: ${AZURE_ORG}
                host: ${AZURE_HOST}
