apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-scaffolder-backend-module-bitbucket-server
  namespace: rhdh
  title: "Scaffolder Backend Module Bitbucket Server"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-bitbucket-server
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-bitbucket-server
  tags:
    - software-templates
spec:
  packageName: "@backstage/plugin-scaffolder-backend-module-bitbucket-server"
  # Tag: bs_1.54.9__0.2.25
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-scaffolder-backend-module-bitbucket-server@sha256:3fac8ac4b6ed2e29f92a07985874f4b3d9c9327a645dbcc9c5ea8d59105974bd"
  version: 0.2.25
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - bitbucket-server-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
