apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-tekton
  namespace: rhdh
  title: Tekton
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/tekton
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/tekton
  tags: []
spec:
  packageName: '@backstage-community/plugin-tekton'
  # Tag: bs_1.52.0__3.41.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-tekton@sha256:a72695f84e1fc5a1a2c22dc59fc31c31c9d5315272bacdc76c997581a51d89d3"
  version: 3.41.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - tekton
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-tekton:
              translationResources:
                - importName: tektonTranslations
                  ref: tektonTranslationRef
              mountPoints:
                - mountPoint: entity.page.ci/cards
                  importName: TektonCI
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isTektonCIAvailable
