apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-scaffolder-backend-module-bitbucket-server
  namespace: rhdh
  title: "Scaffolder Backend Module Bitbucket Server"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-bitbucket-server
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-bitbucket-server
  tags:
    - software-templates
spec:
  packageName: "@backstage/plugin-scaffolder-backend-module-bitbucket-server"
  # Tag: bs_1.49.4__0.2.19
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-scaffolder-backend-module-bitbucket-server@sha256:82a645bc6bfbb05c4c68df5d93e6b896a3921be44917daae2b63502f57f350ad"
  version: 0.2.19
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - bitbucket-server-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
