apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-scaffolder-backend-module-sonarqube
  namespace: rhdh
  title: "Scaffolder Backend Module SonarQube"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-sonarqube
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-sonarqube
  tags:
    - software-templates
spec:
  packageName: "@backstage-community/plugin-scaffolder-backend-module-sonarqube"
  # Tag: bs_1.52.0__2.16.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-scaffolder-backend-module-sonarqube@sha256:63aa0feb08bcdfdba2069afcd025564d7e73648af5f1329dbe92b6530bc21737"
  version: 2.16.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - sonarqube-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
