apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-quay-backend
  namespace: rhdh
  title: "Quay Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/quay
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/quay
  tags: []
spec:
  packageName: "@backstage-community/plugin-quay-backend"
  # Tag: bs_1.52.0__1.17.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-quay-backend@sha256:302d87812b78da1d36e20190f44b75e174d8840844a72801945de9a05e39c305"
  version: 1.17.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - backstage-community-plugin-quay
  appConfigExamples:
    - title: Default configuration
      content:
        quay:
          apiUrl: "https://quay.io"
