apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-scaffolder-backend-module-utils
  namespace: rhdh
  title: "Scaffolder Backend Module Utils"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-utils
  annotations:
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-utils
  tags:
    - software-templates
spec:
  packageName: "@roadiehq/scaffolder-backend-module-utils"
  # Tag: bs_1.54.9__4.2.1
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/roadiehq-scaffolder-backend-module-utils@sha256:2e384cb7696fc19ebb120b28d707ead8b19aa7cc6c200dd956508d6cb75b7068"
  version: 4.2.1
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Roadie
  support: community
  lifecycle: active
  partOf:
    - roadie-scaffolder-util-actions
  appConfigNotRequired: true
  appConfigExamples: []
