apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-events-backend-module-github
  namespace: rhdh
  title: "Events Backend Module GitHub"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should
        raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/events-backend-module-github
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/events-backend-module-github
  tags: []
spec:
  packageName: "@backstage/plugin-events-backend-module-github"
  # Tag: 1.10.0--0.4.6, Build date: 2026-01-29T16:20:49Z
  dynamicArtifact: "oci://quay.io/rhdh/backstage-plugin-events-backend-module-git\
    hub@sha256:c1d17d47aaac41eaeb3ad15c64d904cbad7d93f351cdd69d7aee13b2097329ed"
  version: 0.4.9
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.45.3
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - backstage-plugin-events-backend-module-github
  # From https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.8/html/configuring_dynamic_plugins/configuring-rhdh-events-module#proc-configuring-events-module-for-github
  appConfigExamples:
    - title: Default configuration
      content:
        events:
          http:
            topics:
              - github
          modules:
            github:
              webhookSecret: ${GITHUB_WEBHOOK_SECRET}
