apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-auth-backend-module-oidc-provider
  namespace: rhdh
  title: "Auth Backend Module OIDC Provider"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/auth-backend-module-oidc-provider
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/auth-backend-module-oidc-provider
  tags:
    - authentication
spec:
  packageName: "@backstage/plugin-auth-backend-module-oidc-provider"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-auth-backend-module-oidc-provider:bs_1.52.0__0.4.17
  version: 0.4.17
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - backstage-plugin-auth-backend-module-oidc-provider
  appConfigExamples:
    - title: Default configuration
      content:
        auth:
          providers:
            oidc:
              production:
                clientId: ${OIDC_CLIENT_ID}
                clientSecret: ${OIDC_CLIENT_SECRET}
                metadataUrl: ${OIDC_METADATA_URL}
                signIn:
                  resolvers:
                    - resolver: emailMatchingUserEntityProfileEmail
