apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-auth-backend-module-github-provider
  namespace: rhdh
  title: "Auth Backend Module GitHub Provider"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/auth-backend-module-github-provider
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/auth-backend-module-github-provider
  tags:
    - authentication
spec:
  packageName: "@backstage/plugin-auth-backend-module-github-provider"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-auth-backend-module-github-provider:bs_1.52.0__0.5.4
  version: 0.5.4
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - backstage-plugin-auth-backend-module-github-provider
  appConfigExamples:
    - title: Default configuration
      content:
        auth:
          providers:
            github:
              production:
                clientId: ${GITHUB_CLIENT_ID}
                clientSecret: ${GITHUB_CLIENT_SECRET}
                signIn:
                  resolvers:
                    - resolver: emailMatchingUserEntityProfileEmail
