nodeLinker: node-modules

npmPreapprovedPackages:
  - vitest
  - "@vitest/*"

catalog:
  "@types/node": ^24.13.6
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
