#!/usr/bin/env bash
#
# Merge per-test Istanbul coverage JSONs, generate lcov, and upload to Codecov.
# Coverage is attributed to this overlay repo's commit, flagged per workspace
# (see upload-coverage.sh for the attribution model).
#
# Usage:
#   ./scripts/report-coverage.sh <workspace> [workspace...]
#
# Example:
#   E2E_COLLECT_COVERAGE=true ./run-e2e.sh -w tech-radar
#   ./scripts/report-coverage.sh tech-radar
#
# The script:
#   1. Merges per-test coverage JSONs (written by the _coverageCollector fixture)
#      into a single coverage-final.json using nyc merge
#   2. Remaps bundle coverage onto committed anchor files and writes one
#      coverage/<workspace>/lcov.info per workspace (remap-coverage.cjs)
#   3. Uploads each workspace's lcov to Codecov under its e2e-<workspace> flag
#
# Required environment:
#   CODECOV_TOKEN  - Codecov upload token for this repo's project

set -euo pipefail

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <workspace> [workspace...]" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACES=("$@")

COVERAGE_JSON_DIR="node_modules/.cache/e2e-test-results/coverage"

if ! compgen -G "$REPO_ROOT/$COVERAGE_JSON_DIR/*.json" >/dev/null 2>&1; then
  echo "[INFO] No coverage data found (no instrumented plugins loaded?)"
  exit 0
fi

echo ""
echo "[INFO] Merging coverage data with nyc..."
mkdir -p "$REPO_ROOT/.nyc_output"
npx nyc@18.0.0 merge "$REPO_ROOT/$COVERAGE_JSON_DIR" "$REPO_ROOT/.nyc_output/out.json"

# Remap bundle coverage back to source and emit lcov.
#
# Plugins are instrumented post-build (on the `dist/` and `dist-scalprum/`
# bundles), so the collected coverage is keyed by bundle paths that only existed
# in the publish job's temp dir. `nyc report` cannot resolve those paths here and
# would report 0/0. remap-coverage.cjs applies the source maps nyc embedded
# (`--source-map`) to map coverage onto the original source files and write lcov.
#
# The istanbul libraries are installed into a throwaway prefix so they never land
# in the repo or a workspace's node_modules. Keep these pins in sync with the
# istanbul API that remap-coverage.cjs relies on.
echo "[INFO] Remapping bundle coverage to source and generating lcov..."
# The remap discovers each plugin's owning workspace from the committed anchor
# files (workspaces/*/coverage-anchors/<scalprum-name>, generated by
# generate-coverage-anchors.sh) and writes one coverage/<ws>/lcov.info per
# workspace that contributed coverage, plus the combined coverage/lcov.info.
# Anchors keep lcov paths resolvable in this repo's git tree — Codecov drops
# report paths it can't resolve against the tree.
#
# Wipe previous output first: a stale coverage/<ws>/lcov.info from an earlier
# local run would otherwise be uploaded below, attributed to today's commit.
rm -rf "$REPO_ROOT/coverage"
REMAP_DEPS_DIR=$(mktemp -d)
if ! { npm install --prefix "$REMAP_DEPS_DIR" --no-save --no-audit --no-fund --loglevel=error \
    istanbul-lib-coverage@3.2.2 \
    istanbul-lib-source-maps@5.0.6 \
    istanbul-lib-report@3.0.1 \
    istanbul-reports@3.2.0 \
  && (cd "$REPO_ROOT" && NODE_PATH="$REMAP_DEPS_DIR/node_modules" \
      node "$SCRIPT_DIR/remap-coverage.cjs" "$REPO_ROOT/.nyc_output/out.json" coverage); }; then
  echo "[WARN] Coverage remap/report failed (non-fatal); skipping upload" >&2
  rm -rf "$REMAP_DEPS_DIR"
  exit 0
fi
rm -rf "$REMAP_DEPS_DIR"

# Upload every per-workspace lcov the remap produced, each under its own
# e2e-<workspace> flag. Iterating what was PRODUCED (not what was requested)
# means coverage attributed to a workspace outside this run's -w list is still
# uploaded rather than silently orphaned; upload-coverage.sh validates the
# workspace name. Requested workspaces with no lcov produced no browser
# coverage (backend-only plugins, or uninstrumented images) — note them
# without failing, the nightly legitimately includes such workspaces.
echo "[INFO] Uploading E2E coverage to Codecov..."
shopt -s nullglob
for WS_LCOV in "$REPO_ROOT"/coverage/*/lcov.info; do
  ws=$(basename "$(dirname "$WS_LCOV")")
  "$SCRIPT_DIR/upload-coverage.sh" "$ws" "$WS_LCOV" || \
    echo "[WARN] Coverage upload failed for $ws (non-fatal)"
done
shopt -u nullglob
for ws in "${WORKSPACES[@]}"; do
  if [[ ! -f "$REPO_ROOT/coverage/$ws/lcov.info" ]]; then
    echo "[INFO] No coverage collected for workspace '$ws' — skipping upload"
  fi
done
